schema: ./amplify/backend/api/Fybinder/schema.graphql
documents: ./amplify/backend/api/Fybinder/resolvers
extensions:
  codegen:
    generates:
      ./app/generated-backend.ts:
        plugins:
          - typescript
          - typescript-resolvers
      ./app/generated-frontend.ts:
        plugins:
          - typescript
          - typescript-resolvers
          - typescript-react-apollo
  diff:
    baseSchema: your-base-schema-here
