projects:
  Fybinder:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: graphql/Api.ts
        docsFilePath: graphql
